# Generated by Django 4.1.1 on 2022-12-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='roles',
            new_name='role',
        ),
    ]
